apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ .Values.name }}
    environment: {{ .Values.environment }}
  name: grafana-agent-configmap-{{ .Values.environment }}
  namespace: {{ .Values.namespace }}
data:
  agent.yml: |
    server:
      log_level: debug
    integrations:
      prometheus_remote_write:
      - basic_auth:
          password: ${PROMETHEUS_PASSWORD}
          username: ${PROMETHEUS_USERNAME}
        url: ${PROMETHEUS_URL}
      agent:
        enabled: true
        relabel_configs:
        - action: replace
          source_labels:
          - agent_hostname
          target_label: instance
        - action: replace
          target_label: job
          replacement: integrations/agent-check
        metric_relabel_configs:
        - action: keep
          regex: (prometheus_target_sync_length_seconds_sum|prometheus_target_scrapes_.*|prometheus_target_interval.*|prometheus_sd_discovered_targets|agent_build.*|agent_wal_samples_appended_total|process_start_time_seconds)
          source_labels:
          - __name__
    metrics:
      configs:
      - name: integrations
        remote_write:
        - basic_auth:
            password: ${PROMETHEUS_PASSWORD}
            username: ${PROMETHEUS_USERNAME}
          url: ${PROMETHEUS_URL}
        scrape_configs:
        - job_name: integrations/spring-boot
          static_configs:
            - targets: ['localhost:8081']
          metrics_path: /actuator/prometheus
          metric_relabel_configs:
          - source_labels: [exported_instance]
            target_label: instance
          - regex: ^(exported_instance|deployment_environment|service_instance_id|service_name)$
            action: labeldrop
      global:
        scrape_interval: 60s
    traces:
      configs:
      - name: default
        remote_write:
        - endpoint: ${TEMPO_URL}
          basic_auth:
            username: ${TEMPO_USERNAME}
            password: ${TEMPO_PASSWORD}
        receivers:
          zipkin:
            endpoint: localhost:9411
            parse_string_tags: false
